#!/usr/bin/env bash
#
# Clinical Co-Pilot -- install the eval gate as a PR-blocking git hook.
#
# The MVP's "Gate with eval-driven CI: 50-case golden set, boolean rubrics,
# PR-blocking Git Hook" deliverable. CI is the authoritative blocker (wire
# ops/ci/run-eval-gate.sh into the pipeline -- see that file's header), but a
# LOCAL pre-push hook catches a regression before it ever leaves the machine.
# This installer writes that hook.
#
# It cannot edit the repo's tracked .pre-commit-config.yaml (a core file --
# doing so would violate the module's own additivity invariant, see
# check-additivity.sh), so it installs directly into .git/hooks/ instead, which
# is not tracked. Idempotent: re-running refreshes the hook; an unrelated
# existing pre-push hook is preserved (backed up) rather than clobbered.
#
# Usage (from anywhere in the repo):
#   interface/modules/custom_modules/oe-module-clinical-copilot/ops/ci/install-git-hooks.sh
#
# The installed hook runs the 50-case eval gate and BLOCKS the push (non-zero
# exit) on any rubric regression. If PHP is not on PATH (e.g. a container-only
# dev box) it prints a notice and allows the push -- CI remains the hard gate --
# rather than wedging a developer who has no host PHP toolchain.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "${REPO_ROOT}" ]]; then
  echo "install-git-hooks: not inside a git repository" >&2
  exit 2
fi

HOOKS_DIR="$(git rev-parse --git-path hooks)"
mkdir -p "${HOOKS_DIR}"
HOOK_PATH="${HOOKS_DIR}/pre-push"
MARKER="# >>> clinical-copilot eval gate >>>"

# Preserve an unrelated pre-existing hook once.
if [[ -f "${HOOK_PATH}" ]] && ! grep -qF "${MARKER}" "${HOOK_PATH}"; then
  cp "${HOOK_PATH}" "${HOOK_PATH}.pre-copilot.bak"
  echo "install-git-hooks: backed up existing pre-push hook to ${HOOK_PATH}.pre-copilot.bak"
fi

cat > "${HOOK_PATH}" <<'HOOK'
#!/usr/bin/env bash
# >>> clinical-copilot eval gate >>>
# Auto-generated by oe-module-clinical-copilot/ops/ci/install-git-hooks.sh.
# Blocks a push when the 50-case eval gate regresses (the module's HARD GATE).
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
MODULE="${REPO_ROOT}/interface/modules/custom_modules/oe-module-clinical-copilot"

if ! command -v php >/dev/null 2>&1; then
  echo "clinical-copilot pre-push: php not on PATH -- skipping eval gate locally (CI still enforces it)." >&2
  exit 0
fi

echo "clinical-copilot pre-push: running the 50-case eval gate..." >&2
if ! "${MODULE}/ops/ci/run-eval-gate.sh"; then
  echo "clinical-copilot pre-push: EVAL GATE FAILED -- push blocked. Fix the regression or re-baseline intentionally (run-evals.php --update-baseline)." >&2
  exit 1
fi

# Additivity gate is best-effort locally: it needs a base ref to diff against.
BASE="origin/main"
if git rev-parse --verify --quiet "${BASE}" >/dev/null; then
  if ! "${MODULE}/ops/ci/check-additivity.sh" "${BASE}"; then
    echo "clinical-copilot pre-push: ADDITIVITY GATE FAILED -- push blocked." >&2
    exit 1
  fi
fi

echo "clinical-copilot pre-push: gates green." >&2
# <<< clinical-copilot eval gate <<<
HOOK

chmod +x "${HOOK_PATH}"
echo "install-git-hooks: installed PR-blocking pre-push hook at ${HOOK_PATH}"
echo "  -> runs ops/ci/run-eval-gate.sh (50-case gate) + additivity on every 'git push'."
echo "  -> uninstall by deleting that file (a backup, if any, is at ${HOOK_PATH}.pre-copilot.bak)."
